# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bio-GMOD
version:      0.028
version_from: GMOD.pm
installdirs:  site
requires:
    LWP::UserAgent:                2.023
    MIME::Lite:                    3.01
    Net::SMTP:                     2.26

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
